# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@tmp"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@srv"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@opt"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/f8b691b9-7cd8-4182-b9c5-f402b237d21f";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/50B2-A49C";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/230a04b7-d1ae-490a-b61d-bedbe577811d"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
