# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "CollectionConcurrencyKit" = "0xin8wa0g0jayqdhj62iy6npmb9xs0h0sic4az77l4zw0g5vssyb";
    "SourceKitten" = "0ki9ps2n0ixc135cwidgkbqy8ghp3mz2zc17njny8sf6f33klzqd";
    "swift-argument-parser" = "1jf8g2v6jnr9y2mkmhbw7xqmca5rjrnd4a16yr3yi3lg235m2cwf";
    "swift-syntax" = "1v3brihy22n1w4qlnsjc6anjha4l49yvj6d3yms08hw5smarxl1m";
    "SwiftyTextTable" = "1pzwsa768rwkq4yq65hqw7cr7mip1wzqngrzqjk423g28qs89xx4";
    "SWXMLHash" = "0lij2bg0fcdv75fiacrqy0ilb7l2ahxjxfqqlsdhlnkrl3v9nsjd";
    "Yams" = "0b4lprxl4f6yqq0djnp394mxgmsxm2pljr7fh4f6ihdhnpwfsfvl";
  };
}
