# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@var" "noatime" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "noatime" "compress=zstd" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@srv" "noatime" "compress=zstd" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@opt" "noatime" "compress=zstd" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/8a339334-3ec6-4e7e-9a56-b822f8295672";
      fsType = "btrfs";
      options = [ "subvol=@root" "noatime" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E46-A069";
      fsType = "vfat";
    };

  swapDevices = [ { device = /dev/disk/by-uuid/5855c2b0-5915-4e7a-bb63-5477a7a474b8; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
