# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "compress=zstd" "noatime" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@srv" "compress=zstd" "noatime" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@opt" "compress=zstd" "noatime" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/fca5c6fc-ca87-42af-b524-06ca29fa9d2e";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C07C-2A06";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/7bf4ec90-4f63-459d-8d17-2a129e26ec90"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
